Repository Mendonca78/devops-aula07, pull requests merged in 2018-09, with the labels that each got.

#2 Título: Integrar requisitos v1.0
  docs/requisitos.md
Labels: análise

#9 Integrar implementação v1.0
  src/jogovelha.py
Labels: programacao

#17 Título: Integrar teste de poisicionamento
  docs/teste_de_posicionamento.md
Labels: análise

#18 Integrar implementação v1.0
  src/jogada.py
Labels: programação

#20 Integrar testes v1.1
  src/teste_jogovelha.py
Labels: testes
